# Generated by Django 3.0.9 on 2021-03-19 14:00

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_discountcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[600, 346], upload_to='imageVideo/'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='vidoeCourse/'),
        ),
    ]
