# Generated by Django 3.0.9 on 2021-03-24 12:25

from django.db import migrations, models
import django_resized.forms
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210324_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='image',
            field=models.ImageField(upload_to=home.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[128, 128], upload_to=home.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image2',
            field=models.ImageField(null=True, upload_to=home.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[600, 346], upload_to=home.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='video',
            field=models.FileField(default=None, upload_to=home.models.slugify_upload),
        ),
    ]
