# Generated by Django 3.0.9 on 2021-04-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210406_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractWithSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduon', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('date_req', models.DateTimeField(auto_now_add=True)),
                ('date_pay', models.DateTimeField(auto_now=True)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Speaker')),
            ],
        ),
    ]
