# Generated by Django 3.0.9 on 2021-04-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_billing_contractwithspeaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sp_summa',
            field=models.IntegerField(default=0),
        ),
    ]
