# Generated by Django 3.0.9 on 2021-04-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_order_sp_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='place_number',
            field=models.IntegerField(default=0),
        ),
    ]
