# Generated by Django 3.0.9 on 2021-04-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210417_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentVideo',
            new_name='CommentCourse',
        ),
    ]
