# Generated by Django 3.0.9 on 2021-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210419_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_value', models.IntegerField(default=0)),
                ('speaker_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='speaker',
            name='own_ref_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='own_ref_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='parent_ref_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
