# Generated by Django 3.0.9 on 2021-05-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210503_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='has_course',
            field=models.BooleanField(default=False),
        ),
    ]
