# Generated by Django 3.0.9 on 2021-08-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_aboutusnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about_course',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='for_whom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='get_from_course',
            field=models.TextField(blank=True, null=True),
        ),
    ]
