# Generated by Django 3.0.9 on 2021-08-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210817_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCodeSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
    ]
