# Generated by Django 3.0.9 on 2021-08-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20210823_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user',
            new_name='speaker',
        ),
    ]
