# Generated by Django 3.0.9 on 2021-12-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20211109_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='wallet_expire',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='wallet_expire',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
