# Generated by Django 3.0.9 on 2022-01-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20220115_1155'),
    ]

    operations = [
    ]
