# Generated by Django 3.0.9 on 2022-01-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20220115_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
