# Generated by Django 3.0.9 on 2022-01-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_remove_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryvideo',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='course_categories', to='home.CategoryVideo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_tags',
            field=models.ManyToManyField(blank=True, related_name='course_tags', to='home.CourseTag'),
        ),
        migrations.AlterField(
            model_name='forwhomcourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwhom', to='home.Course'),
        ),
        migrations.AlterField(
            model_name='requirementscourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courserequirements', to='home.Course'),
        ),
        migrations.AlterField(
            model_name='whatyoulearn',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatyoulearn', to='home.Course'),
        ),
    ]
