# Generated by Django 3.0.9 on 2022-02-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20220205_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='place_number',
            field=models.IntegerField(default=0),
        ),
    ]
