# Generated by Django 3.0.9 on 2022-02-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_users_date_of_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reason_of_ban',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
