# Generated by Django 3.0.9 on 2022-02-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_users_reason_of_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='reason_of_ban',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
