# Generated by Django 3.0.9 on 2021-12-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniredpay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHoldLimitTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(default=3, verbose_name='Kun')),
            ],
            options={
                'verbose_name_plural': "Foydalanuvchilarga to'lovni qaytarish muddati",
            },
        ),
        migrations.RemoveField(
            model_name='payforbalance',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payforbalance',
            name='uu_id',
        ),
        migrations.AddField(
            model_name='payforbalance',
            name='tr_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
