# Generated by Django 3.0.9 on 2021-12-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniredpay', '0002_auto_20211211_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payforbalance',
            name='card_mask',
        ),
    ]
