# Generated by Django 3.0.9 on 2022-03-15 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_discount'),
        ('uniredpay', '0003_remove_payforbalance_card_mask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Speaker')),
            ],
        ),
    ]
