# Generated by Django 3.0.9 on 2021-03-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=13)),
                ('amount', models.IntegerField()),
                ('account', models.CharField(max_length=255)),
                ('create_time', models.FloatField(blank=True, default=0)),
                ('perform_time', models.FloatField(blank=True, default=0)),
                ('cancel_time', models.FloatField(blank=True, default=0)),
                ('state', models.SmallIntegerField()),
                ('reason', models.SmallIntegerField(blank=True, default=0)),
                ('receivers', models.CharField(blank=True, max_length=500, null=True)),
                ('order_id', models.IntegerField()),
            ],
        ),
    ]
