# Generated by Django 3.0.9 on 2021-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210324_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='card_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='card_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
