# Generated by Django 3.0.9 on 2021-04-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210405_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='summa',
            field=models.IntegerField(default=0),
        ),
    ]
