# Generated by Django 3.0.9 on 2021-04-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210409_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
    ]
