# Generated by Django 3.0.9 on 2021-04-17 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_commentvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='commentvideo',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Course'),
            preserve_default=False,
        ),
    ]
