# Generated by Django 3.0.9 on 2021-05-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_orderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='regbonus',
            name='summa_full',
            field=models.IntegerField(default=0),
        ),
    ]
