# Generated by Django 3.0.9 on 2021-06-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210527_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
