# Generated by Django 3.0.9 on 2021-08-18 10:45

from django.db import migrations
import django_resized.forms
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_speaker_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='image2',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to=home.models.slugify_upload),
        ),
    ]
