# Generated by Django 3.0.9 on 2021-10-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20210823_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='for_eduon',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
