# Generated by Django 3.0.9 on 2021-10-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_order_for_eduon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='for_eduon',
            field=models.IntegerField(default=0),
        ),
    ]
