# Generated by Django 3.0.9 on 2021-10-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20211010_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='card_expire',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
