# Generated by Django 3.0.9 on 2021-11-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_course_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankcourse',
            old_name='tashkil_value',
            new_name='content_value',
        ),
        migrations.AddField(
            model_name='rankcourse',
            name='video_value',
            field=models.IntegerField(default=0),
        ),
    ]
