# Generated by Django 3.0.9 on 2022-01-15 06:55

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_order_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTrailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_file', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to=home.models.slugify_upload)),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Fikr', 'verbose_name_plural': 'Fikrlar'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Davlat', 'verbose_name_plural': 'Davlatlar'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Til', 'verbose_name_plural': 'Tillar'},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name': "To'lov tarixi", 'verbose_name_plural': "To'lovlar tarixi"},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Tuman', 'verbose_name_plural': 'Tumanlar'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': 'Spiker', 'verbose_name_plural': 'Spikerlar'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='videocourse',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.AddField(
            model_name='categoryvideo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.CategoryVideo'),
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(related_name='course_categories', to='home.CategoryVideo'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Elementary', 'Elementary'), ('Intermediate', 'Intermediate')], default='Beginner', max_length=12),
        ),
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_author', to='home.Speaker'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couse_category', to='home.CategoryVideo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_language', to='home.Language'),
        ),
        migrations.CreateModel(
            name='WhatYouLearn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatyoulearn', to='home.Course')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courserequirements', to='home.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ForWhomCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwhom', to='home.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_tags',
            field=models.ManyToManyField(related_name='course_tags', to='home.CourseTag'),
        ),
        migrations.AddField(
            model_name='course',
            name='trailer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_trailer', to='home.CourseTrailer'),
        ),
    ]
