# Generated by Django 3.0.9 on 2022-01-26 11:34

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20220118_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to=home.models.slugify_upload),
        ),
    ]
