# Generated by Django 3.0.9 on 2022-01-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20220126_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
