# Generated by Django 3.0.9 on 2022-01-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20220126_1652'),
        ('home', '0050_phonecode_created_at'),
    ]

    operations = [
    ]
