# Generated by Django 3.0.9 on 2022-01-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_merge_20220127_1014'),
        ('home', '0052_merge_20220126_1706'),
    ]

    operations = [
    ]
