# Generated by Django 3.0.9 on 2022-02-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_merge_20220129_1550'),
        ('home', '0053_merge_20220127_1353'),
    ]

    operations = [
    ]
