# Generated by Django 3.0.9 on 2022-02-05 08:45

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_merge_20220205_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('place_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1280, 720], upload_to=home.models.slugify_upload),
        ),
        migrations.CreateModel(
            name='IsFinished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('courseModule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.CourseModule')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.File')),
            ],
        ),
    ]
