# Generated by Django 3.0.9 on 2022-02-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('home', '0055_auto_20220205_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='isfinished',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='isfinished',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Users'),
        ),
        migrations.AddField(
            model_name='isfinished',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.VideoCourse'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course', verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='file',
            name='courseModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.CourseModule'),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='courseModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.CourseModule'),
        ),
    ]
