# Generated by Django 3.0.9 on 2022-02-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_file_place_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='date_of_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
