# Generated by Django 3.0.9 on 2022-02-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_speaker_reason_of_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_of_release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
