# Generated by Django 3.0.9 on 2022-02-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20220225_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecode',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
