# Generated by Django 3.0.9 on 2022-03-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_auto_20220317_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='status',
        ),
    ]
