# Generated by Django 3.0.9 on 2022-03-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_auto_20220317_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire_day',
            field=models.DateField(),
        ),
    ]
